### ISSUE TITLE
Index out of range while inputing a folder (using -f) or a 1-size n puzzle (with random settings)

### ISSUE THREAD

**Issue by 0auBSQ** [tdelabro/n-puzzle#1]
(Folder)
```
go run n_puzzle/* -H c -f testFiles/invalids
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.readFile(0x7fffd0c25896, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:27 +0xcf7
main.main()
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:111 +0x217
exit status 2
```
(1-size)
```
go run n_puzzle/* -i 100 -s 1 -H c
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.Generator(0x1, 0xc0000c4010, 0x6, 0x6)
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/goal_generator.go:16 +0x139
main.main()
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:118 +0x306
exit status 2
```

**Comment by tdelabro** [comment]
Fixed
