### ISSUE TITLE
Index out of range with empty file (error test 04)

### ISSUE THREAD

**Issue by 0auBSQ** [tdelabro/n-puzzle#3]
./n-puzzle -f testFiles/rmarraccs_lunatic_tests/error/04_empty_file.oof
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.readFile(0x7fffecad777d, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:27 +0xcf7
main.main()
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:112 +0x387

**Comment by 0auBSQ** [comment]
(Same error occurs with a folder : ./n-puzzle -f testFiles/rmarraccs_lunatic_tests/error
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.readFile(0x7fffc0d7527d, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:27 +0xcf7
main.main()
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:112 +0x387
Will fix it tomorrow if I have some time)

**Comment by 0auBSQ** [comment]
(Same error occurs with splitted_puzzle : ./n-puzzle -f testFiles/invalids/splitted_puzzle.txt
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.readFile(0x7fffce1306ad, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:40 +0xcf0
main.main()
        /mnt/d/Desktop/42UltimateFolder/Projects/Npuzzle42/n_puzzle/n_puzzle.go:112 +0x387)

**Comment by 0auBSQ** [comment]
Fixed
